#define DEFAULT_ALLOCATOR_ARENA_PAGES 16

#ifdef __unix__

  #include <unistd.h>
  #define DEFAULT_ALLOCATOR_ARENA_PAGESIZE (_SC_PAGESIZE * 8)

#else
  #define DEFAULT_ALLOCATOR_ARENA_PAGESIZE 4096
#endif

#define ARENA_SIZE (DEFAULT_ALLOCATOR_ARENA_PAGESIZE * DEFAULT_ALLOCATOR_ARENA_PAGES)
